project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testapp/urls.py
from django.contrib import admin
from django.urls import path
from testapp import views
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('base',views.base,name="base"),
    # path('msgs',views.msgs,name="msgs"),
    # path('demo/',views.demo,name="demo"),
    path('machin1',views.first_machine,name="machin1"),
    path('machin2',views.second_machine,name="machin2"),
    path('home/',views.home,name="home"),
    path('tables/',views.data_tabel,name="tables"),
    path('charts/',views.charts,name="charts"),

    path('', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    
    path('password/', auth_views.PasswordChangeView.as_view(template_name='change_password.html')),
    
    
    # reset password urls
    # path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    
    
    
    
    
 
    
    # urls masters
    # alert_masters 
    path('alert_details/', views.alert_details, name='alert_details'),
    path('add_alertmaster/', views.add_alertmaster, name='add_alertmaster'),
    path('updatealert/<int:id>/', views.update_alert, name='update_alert'),
    path('del/<int:id>/', views.delete_alert, name='delete_alert'),
    
    # device_detials 
    path('device_details/', views.device_details, name='device_details'),
    path('add_device/', views.add_device, name='add_device'),
    path('updatedevice/<int:id>/', views.update_device, name='update_device'),
    path('dele/<int:id>/', views.delete_device, name='delete_device'),

    # company_info
    path('company/', views.company, name='company'),
    path('add_company/', views.add_company, name='add_company'),
    path('updateinfo/<int:id>/', views.update_data, name='updatedata'),
    path('delet/<int:id>/', views.delete_data, name='deletedata'),
    
    # user_details 
    path('user_details/', views.user_details, name='user_details'),
    path('add_user/', views.add_user, name='add_user'),
    path('updateuser/<int:id>/', views.update_user, name='update_user'),
    path('deletes/<int:id>/', views.deleteuser, name='deleteuser'),
   
   
   
   
   
   

# demo template (only for practice )
    # path('temp_one/', views.temp_one, name='temp_one'),
    
    # dynamic url asel id integer mde yete <int:(conveter)id>
    

]

testapp/models.py
from django.db import models

from twilio.rest import Client

# Create your models here.
class scan_data(models.Model):
    slave_id = models.IntegerField()
    first_scan = models.CharField(max_length=50)
    first_scan_datetime = models.DateTimeField()
    air_pressure = models.CharField(max_length=50)
    leak_rate = models.CharField(max_length=50)
    ok_signal = models.CharField(max_length=10)
    test_datetime = models.DateTimeField()
    second_scan = models.CharField(max_length=50)
    second_scan_datetime = models.DateTimeField()
    device_id = models.CharField(max_length=50)
    varient = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'scan_data'
    
        

class print_data(models.Model):
    piid = models.IntegerField()
    qrcode = models.CharField(max_length=50)
    name = models.CharField(max_length=20)
    extra1 = models.BigIntegerField()
    extra2 = models.CharField(max_length=20)
    extra3 = models.CharField(max_length=20)
    date_time = models.DateTimeField()
    add_date = models.DateTimeField()
    device_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'print_data'



        
        
class Company_Info(models.Model):
    company_id = models.AutoField(primary_key=True)
    company_name = models.CharField(max_length=10)
    company_address = models.CharField(max_length=50)
    company_logo = models.ImageField(upload_to='images',default="")
    company_image= models.ImageField(upload_to='images',default="")
    # created_date =  models.DateTimeField(auto_now_add=True)
    created_date =  models.DateField(blank=True,null= True)
    updated_date =  models.DateTimeField(auto_now_add=True)
    deleted_date =  models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.company_name 
        
        
class Device_Details(models.Model):
    device_id = models.AutoField(primary_key=True)
    
    company_id = models.ForeignKey(Company_Info, on_delete = models.CASCADE)
    
    device_name = models.CharField(max_length=20)
    time_stamp = models.TimeField(auto_now_add=True)
    installed_date =  models.DateField()
    # extra1 = models.CharField(max_length=20)
    # extra2 = models.CharField(max_length=20)
    # extra3 = models.CharField(max_length=20)
    
    def __str__(self):
        return self.device_name
        
    
    

class Alert_Master(models.Model):
    alert_master_id = models.AutoField(primary_key=True)
    
    device_id = models.ForeignKey(Device_Details, on_delete=models.CASCADE)
    
    alert_massage = models.CharField(max_length=20)
    register = models.IntegerField()
    counts = models.IntegerField()
    date_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.register)
    
    # def save(self, *args, **kwargs):
        #if test_result is less than 80 execute this
        # if self.register < 1:
        #     #twilio code
        #     account_sid = 'ACbf006fd11a72689c80ec0bc8e8012c02'
        #     auth_token = 'd128f871cf42beae11e3dae639eadb9d'
        #     client = Client(account_sid, auth_token)

        #     message = client.messages.create(
        #                             body=f'your Plc register number is {self.register} and msg is {self.alert_massage} and count is {self.counts}',
        #                             from_='+13089373173',
        #                             to='+918329853765' 
        #                         )
        # return super().save(*args, **kwargs)
    
      
    
class User_Details(models.Model):
    user_id = models.AutoField(primary_key=True)
    company_id = models.ForeignKey(Company_Info, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email_id = models.EmailField(max_length = 254,unique=True)
    phone_number = models.CharField(max_length=12,unique=True)
    address = models.CharField(max_length=50)


class Alert_Data(models.Model):
    alart_id = models.AutoField(primary_key=True)
    iot_id = models.ForeignKey(Company_Info, on_delete=models.CASCADE)
    device_id = models.IntegerField()
    register = models.IntegerField
    date_time = models.DateTimeField(auto_now_add=True)
    time_stamp = models.DateTimeField(auto_now_add=True)

    
    

        

    
    
    
    
  

testapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib import messages
from matplotlib.style import context
from .forms import *
from testapp.models import scan_data, print_data, Alert_Master
from datetime import datetime
from django.db.models import Q
from django.core.mail import send_mail


# Create your views here.


def base(request):
    # reg = Alert_Master.objects.filter(register=0)
    # msg = Alert_Master.objects.filter(alert_massage)
    context = {
        # 'reg':reg,
        # 'msg' :msg,
    }
    # print(reg)
    # return render(request, 'base.html',context)


def first_machine(request):
    return render(request, 'machine1.html')


def second_machine(request):
    return render(request, 'machine2.html')


# def demo(request):
#     return render(request,'demo.html', context)



def home(request):
    # machin_data = scan_data.objects.all()
    machin_data1 = scan_data.objects.filter(ok_signal='(ok)').count()
    machin_data2 = scan_data.objects.filter(ok_signal='None').count()
    machin_data3 = scan_data.objects.filter(ok_signal='(AL)').count()
    machin_data4 = scan_data.objects.filter(ok_signal='(F )').count()
    total = [machin_data1+machin_data2+machin_data3+machin_data4]


    from datetime import datetime
    import mysql.connector
    from django.db import connection
    
    from django.db.models import Count

    
    from datetime import datetime
    from django.db.models import Count
    from django.contrib.auth.models import User
    
    cursor = connection.cursor()

    # ------------------Live Progress Chart-----------------------
    from django.db import connection

    cursor = connection.cursor()
    cursor.execute('''select hour(first_scan_datetime),count(ok_signal) from scan_data where ok_signal= '(ok)' group by hour(first_scan_datetime) order by hour(first_scan_datetime)''')
    row = cursor.fetchall()
    hour,count=zip(*row)
    hour1 = ','.join(map(str,hour))
    count1 = ','.join(map(str,count))
    # print(hour1)
    # print(count1)

    cursor1 = connection.cursor()
    cursor1.execute('''select hour(first_scan_datetime),count(ok_signal) from scan_data where ok_signal= 'None' group by hour(first_scan_datetime) order by hour(first_scan_datetime)''')
    row1 = cursor1.fetchall()
    hour,count=zip(*row1)
    # hour1 = ','.join(map(str,hour))
    count2 = ','.join(map(str,count))
    # print(count2)
    
    # ==============================for notification badge ===========================================================
    
    reg = Alert_Master.objects.filter(register=0)
        
    context = {
        # 'mystring':mystring,
        # 'machin_data':machin_data,
        'machin_data1': machin_data1,
        'machin_data2': machin_data2,
        'machin_data3': machin_data3,
        'total': total,
        'hour1': hour1,
        'count1':count1,
        'count2':count2,
        'reg':reg,
        
    }
    return render(request, 'index.html', context)


# from django.shortcuts import render
# from twilio.rest import Client
# from django.http import HttpResponse

# def msgs(request):
#     reg = Alert_Master.objects.filter(register=0)
#     if reg < 1:
        
#         account_sid = 'ACbf006fd11a72689c80ec0bc8e8012c02'
#         auth_token = 'd128f871cf42beae11e3dae639eadb9d'
#         client = Client(account_sid, auth_token)

#         message = client.messages.create(
#                                     body=f'your Plc register number is {register} and msg is {alert_massage}',
#                                     from_='+13089373173',
#                                     to='+917498335002' 
#                                 )
        
#         return HttpResponse('Message Sent Successfully..')
#     else:
#         return HttpResponse('error')


def data_tabel(request):
    machin_data = scan_data.objects.all()
    context = {
        'machin_data': machin_data,

    }
    return render(request, 'table.html',context)


def charts(request):
    machin_data1 = scan_data.objects.filter(ok_signal='(ok)').count()
    machin_data2 = scan_data.objects.filter(ok_signal='None').count()
    machin_data3 = scan_data.objects.filter(ok_signal='(AL)').count()
    machin_data4 = scan_data.objects.filter(ok_signal='(F )').count()
    total = [machin_data1+machin_data2+machin_data3+machin_data4]
    context = {
        # 'mystring':mystring,
        # 'machin_data':machin_data,
        'machin_data1': machin_data1,
        'machin_data2': machin_data2,
        'machin_data3': machin_data3,
        'total': total,
       
    }
    return render(request, 'charts.html',context)


# login page
def login_user(request):
	# if not request.user.is_authenticated:
	if request.method == 'POST':  # if someone fills out form , Post it
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:  # if user exist
			login(request, user)
			messages.success(request, ('succesfully Login !!!!..'))
			return redirect('home')  # routes to 'home' on successful login
		else:
			messages.error(request, ('Please enter a correct username and password.'))
			return redirect('login')  # re routes to login page upon unsucessful login
	else:
		return render(request, 'login.html', {})
	# else:
	# 	return redirect('home')

# logout page


def logout_user(request):
	logout(request)
	messages.error(request, ('Youre now logged out'))
	return redirect('login')

# register page


def register_user(request):

	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			# username = form.cleaned_data['username']
			# password = form.cleaned_data['password1']
			# user = authenticate(username=username, password=password)
			# login(request,user)
			messages.success(request, ('Youre now registered'))
			return redirect('login')
	else:
		form = SignUpForm()

	context = {'form': form}
	return render(request, 'register.html', context)


def edit_profile(request):
    if request.user.is_authenticated:
        if request.method =='POST':
            form = EditUserProfileForm(request.POST, instance= request.user)
            if form.is_valid():
                form.save()
                messages.success(request, ('Your Prifile Updated'))
                return redirect('home')
        else: 		#passes in user information
            form = EditUserProfileForm(instance= request.user)

        context = {'form': form}
        return render(request, 'edit_profile.html',context)
    else:
        return redirect('home')

# this urls used for chagne user password 
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView


def PasswordChangeView(PasswordChangeView):
    from_class = passwordchangingforms
    success_url = reverse_lazy('login')


def forgot_password(request):
    return render(request, 'forgot_password.html')


# MASTERS
######################  Company Information  ######################
def company(request):
    cm = Company_Info.objects.all()
    context = {
		'cm': cm,
 	}
    return render(request, 'masters/company/company.html', context)

def add_company(request):
    if request.method == "POST":
        company_name = request.POST["company_name"]
        company_address = request.POST["company_address"]
        company_logo = request.FILES["company_logo"]
        company_image = request.FILES["company_image"]
        created_date=request.POST["created_date"]
        # updated_date=request.POST["updated_date"]
        # deleted_date=request.POST["deleted_date"]
        info_company = Company_Info.objects.create(
            company_name=company_name, company_address=company_address, created_date=created_date, company_logo=company_logo, company_image=company_image)
        info_company.save()
        return redirect('company')

    return render(request, 'masters/company/add_company.html')

# this function will update/delete
def update_data(request, id):
    if request.method == "POST":
        pi = Company_Info.objects.get(pk=id)
        fm = company_form(request.POST, request.FILES, instance=pi)
        if fm.is_valid():
            fm.save()
        return redirect('company')
    else:
        pi = Company_Info.objects.get(pk=id)
        fm = company_form(instance=pi)
        
    return render(request, 'masters/company/updatecompany.html', {'form': fm})

# this function will delete
def delete_data(request, id):  
    if request.method == "POST":
        pi = Company_Info.objects.get(pk=id)  
        pi.delete()
        return redirect('company')



#######################  Device Details #########################
def device_details(request):
    cm = Device_Details.objects.all()
    context = {
		'cm': cm,
 	}
    return render(request, 'masters/device/device_details.html', context)

def add_device(request):
    cm = Company_Info.objects.all()
    if request.method == 'POST':
	    form = device_registration_form(request.POST)
	    if form.is_valid():
		    form.save()
		    # messages.success(request,("Employee REsignation Added successful  !!!"))
		    return redirect('device_details')
    else:
	    form = device_registration_form()

    context = {
		'cm': cm,
		'form': form
 	}
    return render(request, 'masters/device/add_device.html', context)

def update_device(request, id):
    if request.method == "POST":

testapp/templates/masters/company/add_company.html
{% extends 'base.html' %} 
{% block content %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'css/tempone.css' %}" rel="stylesheet" />
    <title>Document</title>
  </head>
  <body>
    <div class="container-fluid px-1 py-2 mx-auto">
      <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 ">
          {% comment %} <h3 class="text-center "></h3> {% endcomment %}
          <div class="card">
            <h3 class="text-center  mb-4 text-primary ">Company Information</h3>

            <form class="form-card" action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row justify-content-between text-left">


                <div class="form-group col-sm-12 flex-column d-flex mb-2">
                  <label for="inputcompanyname" class="text-black">Company Name :</label>
                  <input type="text" name="company_name" placeholder="Enter your Company Name"/>
                </div>

                <div class="form-group col-sm-12 flex-column d-flex mb-2">
                  <label for="inputcompanyid" class="text-black">Company Address :</label>
                  <input type="text" placeholder="Enter company address" name="company_address"/>
                </div>

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputdate" class="text-black">Created Date :</label>
                  <input type="date" name="created_date" placeholder=""/>
                </div> 

                {% comment %} <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputdate" class="text-black">Updated Date :</label>
                  <input type="date" name="updated_date" placeholder=""/>
                </div>

                
                <div class="form-group col-sm-6 flex-column d-flex mb-4">
                  <label for="inpurtext" class="text-black">Deleted Date :</label>
                  <input type="date" name="deleted_date" placeholder=""/>
                </div> {% endcomment %}

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputfile" class="text-black">Company Logo :</label>
                  <input type="file" name="company_logo" accept="image/*" />
                </div>

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputfile" class="text-black">Company Image:</label>
                  <input type="file" name="company_image" accept="image/*"/>
                </div>

                <div class="mt-4 mb-0">
                  <div class="d-grid"><button type="submit" class="btn btn-primary btn-block">Submit</button></div>
                </div>

              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock %}

testapp/templates/masters/company/company.html
{% extends 'base.html' %}

{% block content %}
{% comment %} <style>
    table {
        table-layout:fixed;
        width:100%;
        }
    
        .tablewrapper { 
            overflow-x:none;
            overflow-y:scroll;
        }
     
</style> {% endcomment %}

<div class="container border-black mt-4">
    <div class="row mt-2">
        <div class="col-lg-12 d-flex justify-content-between align-items-center mt-2 ">
            <div >
            <h4 class="text-primary text-white d-flex">Company Information List</h4>
            </div>
            <div>
            <a class="btn btn-success d-flex" href="{% url 'add_company' %}">+ Add Company</a>
            </div> 
        </div>
        <hr class="text-bg-dark" width="100%;">
        <div class="card mb-4 text-center ">
        <!-- <div class="card-header">
            <i class="fas fa-table me-1"></i>
            DataTable Example
        </div> -->
            <div class="card-body mt-2 tablewrapper ">
                <table id="datatablesSimple" class="table table-responsive">
                    <thead >
                        <tr>
                            <th>company_id</th>
                            <th>company_name</th>
                            <th>company_addr</th>
                            <th>company_logo</th>
                            <th>company_image</th>
                            <th>created_date</th>
                            <th>action</th>
                        </tr>
                    </thead>
                    <!-- <tfoot>
                        <tr>
                            <th>company_name</th>
                            <th>company_address</th>
                            <th>company_logo</th>
                            <th>company_image</th>
                            <th>created_date</th>
                            <th>company_id</th>
                        </tr>
                    </tfoot> -->
                    <tbody>
                        {% for cd in cm %}
                        <tr>
                            <td scope="row">{{forloop.counter}}</td>
                            <td>{{cd.company_name}}</td>
                            <td>{{cd.company_address}}</td>
                            {% comment %} <td>{{cd.company_logo}}</td> {% endcomment %}
                            <td>{% if cd.company_logo %}<img src="/media/{{ cd.company_logo }}" class="img img-responsive rounded-pill" height="30px" width="40px">{% endif %}</td>
                            {% comment %} <td>{{cd.company_image}}</td> {% endcomment %}
                            <td>{% if cd.company_image %}<img src="/media/{{ cd.company_image }}" class="img img-responsive rounded-pill" height="30px" width="40px">{% endif %}</td>
                            <td>{{cd.created_date}}</td>
                            <td>
                                <a href="{% url 'updatedata' cd.company_id %}" class="btn btn-warning btn-sm">Edit</a>
                                <form action="{% url 'deletedata' cd.company_id %}" method="POST" class="d-inline">{% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-sm" value="delete">
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    

    
</div>























{% endblock %}

testapp/templates/masters/company/updatecompany.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'css/tempone.css' %}" rel="stylesheet" />
    <title>Update</title>
  </head>
  <body>
    <div class="container-fluid px-1 py-2 mx-auto">
      <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 "> 
          {% comment %} <h3 class="text-center "></h3> {% endcomment %}
          <div class="card">
            <h3 class="text-center  mb-4 text-primary "> Edit Company Information</h3>

            <form class="form-card" action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}

              {% comment %} {{ form.as_p}} {% endcomment %}
              <div class="row justify-content-between text-left">
                <div class="form-group col-sm-12 flex-column d-flex mb-2">
                  <label for="id_company_name" class="text-black">Company Name :</label>
                  {% render_field form.company_name %} 
                </div>

                <div class="form-group col-sm-12 flex-column d-flex mb-2">
                  <label for="inputcompanyid" class="text-black">Company Address :</label>
                  {% render_field form.company_address %} 
                </div>

                {% comment %} <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputdate" class="text-black">Updated Date :</label>
                  <input type="date" name="updated_date" placeholder=""/>
                </div>

                
                <div class="form-group col-sm-6 flex-column d-flex mb-4">
                  <label for="inpurtext" class="text-black">Deleted Date :</label>
                  <input type="date" name="deleted_date" placeholder=""/>
                </div> {% endcomment %}

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputfile" class="text-success">Company Logo :</label>
                  {% render_field form.company_logo  class="text-danger"%} 
                </div>

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputfile" class="text-success">Company Image:</label>
                  {% render_field form.company_image class="text-danger" %}
                </div>

                <div class="form-group col-sm-6 flex-column d-flex mb-2">
                  <label for="inputdate" class="text-black">Created Date :</label>
                  {% render_field form.created_date class="form-control" %} 
                </div> 

                <div class="mt-4 mb-0">
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary btn-block">Update</button>
                    </div>
                </div>

              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </body>
</html> 



{% endblock %}